<a href="https://colab.research.google.com/github/nqas/home_credit_default_risk/blob/main/starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

Please duplicate this file before conducting your own data exploration as conflicts can occur.

Information on the dataset can be found here: https://www.kaggle.com/c/home-credit-default-risk

![](https://storage.googleapis.com/kaggle-media/competitions/home-credit/home_credit.png)

In [ ]:
# Follow the instructions and paste the authorisation code when prompted
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
%load_ext google.colab.data_table

In [ ]:
# Load data from shared folder (takes about 1.5 minutes)
path = "/content/drive/My Drive/DM Project/home-credit-default-risk/"

filenames = ["sample_submission","previous_application","installments_payments",
"credit_card_balance","bureau_balance","bureau","application_train",
"application_test","POS_CASH_balance"]

for filename in filenames: vars()[filename] = pd.read_csv(path + filename + ".csv")
HomeCredit_columns_description = pd.read_csv(path + "HomeCredit_columns_description" + ".csv", engine='python')

The google.colab.data_table extension is already loaded. To reload it, use:
  %reload_ext google.colab.data_table

In [ ]:
HomeCredit_columns_description

     Unnamed: 0  ...                                Special
0             1  ...                                    NaN
1             2  ...                                    NaN
2             5  ...                                    NaN
3             6  ...                                    NaN
4             7  ...                                    NaN
..          ...  ...                                    ...
214         217  ...                                    NaN
215         218  ...  time only relative to the application
216         219  ...  time only relative to the application
217         220  ...                                    NaN
218         221  ...                                    NaN

[219 rows x 5 columns]

# Application Train/Test

In [ ]:
application_train.sample(20)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
141247,263766,0,Cash loans,F,N,N,0,202500.0,810000.0,29223.0,810000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.026392,-17749,-2976,-1130.0,-1234,NaN,1,1,0,1,0,0,High skill tech staff,2.0,2,2,FRIDAY,18,0,0,0,0,0,0,Medicine,0.657966,0.745114,0.595456,0.1175,NaN,0.9955,NaN,NaN,0.08,0.0345,0.6250,NaN,NaN,NaN,0.1229,NaN,NaN,0.1197,NaN,0.9955,NaN,NaN,0.0806,0.0345,0.6250,NaN,NaN,NaN,0.1280,NaN,NaN,0.1187,NaN,0.9955,NaN,NaN,0.08,0.0345,0.6250,NaN,NaN,NaN,0.1251,NaN,NaN,NaN,block of flats,0.1243,"Stone, brick",No,5.0,0.0,5.0,0.0,-348.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0,2.0
285217,430323,0,Cash loans,F,N,Y,0,157500.0,942300.0,27679.5,675000.0,Family,Pensioner,Secondary / secondary special,Married,House / apartment,0.010147,-22350,365243,-12614.0,-4476,NaN,1,0,0,1,1,0,NaN,2.0,2,2,FRIDAY,13,0,0,0,0,0,0,XNA,NaN,0.518903,0.795803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1845.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
122263,241755,1,Cash loans,M,N,N,0,252000.0,675000.0,20668.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.028663,-21968,-1236,-6673.0,-4704,NaN,1,1,0,1,1,0,Managers,2.0,2,2,THURSDAY,11,0,0,0,0,0,0,Business Entity Type 3,NaN,0.044777,0.352340,0.0838,0.0561,0.9921,NaN,NaN,0.08,0.0690,0.3471,NaN,NaN,NaN,0.0501,NaN,0.0036,0.0756,0.0488,0.9896,NaN,NaN,0.0806,0.0690,0.3333,NaN,NaN,NaN,0.0472,NaN,0.0000,0.0749,0.0598,0.9896,NaN,NaN,0.08,0.0690,0.3333,NaN,NaN,NaN,0.0472,NaN,0.0000,NaN,NaN,0.0824,Mixed,No,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
300308,447913,0,Cash loans,F,N,N,0,108000.0,450000.0,16294.5,450000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.026392,-22915,365243,-742.0,-4047,NaN,1,0,0,1,1,0,NaN,2.0,2,2,FRIDAY,14,0,0,0,0,0,0,XNA,NaN,0.708085,0.691021,0.0866,0.0316,0.9791,NaN,NaN,0.08,0.0345,0.4583,NaN,0.0490,NaN,0.0436,NaN,0.4274,0.0882,0.0328,0.9791,NaN,NaN,0.0806,0.0345,0.4583,NaN,0.0502,NaN,0.0454,NaN,0.4525,0.0874,0.0316,0.9791,NaN,NaN,0.08,0.0345,0.4583,NaN,0.0499,NaN,0.0444,NaN,0.4364,NaN,block of flats,0.1272,Panel,No,0.0,0.0,0.0,0.0,-1555.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
98538,214409,0,Revolving loans,M,Y,N,1,450000.0,675000.0,33750.0,675000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.020713,-13945,-373,-5068.0,-4753,3.0,1,1,0,0,0,1,Managers,3.0,3,2,MONDAY,14,0,0,0,0,0,0,Business Entity Type 1,0.762411,0.471648,0.627991,0.0619,0.1298,0.9742,0.6464,0.0058,0.00,0.1379,0.1667,0.2083,0.0551,0.0504,0.0506,0.0000,0.0000,0.0630,0.1347,0.9742,0.6602,0.0059,0.0000,0.1379,0.1667,0.2083,0.0563,0.0551,0.0528,0.0000,0.0000,0.0625,0.1298,0.9742,0.6511,0.0059,0.00,0.1379,0.1667,0.2083,0.0560,0.0513,0.0515,0.0000,0.0000,reg oper account,block of flats,0.0430,"Stone, brick",No,1.0,0.0,1.0,0.0,-1.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
130109,250903,0,Cash loans,F,Y,Y,1,270000.0,1314886.5,88357.5,1260000.0,Unaccompanied,Pensioner,Higher education,Married,House / apartment,0.072508,-15163,365243,-9207.0,-3048,7.0,1,0,0,1,1,0,NaN,3.0,1,1,SUNDAY,11,0,0,0,0,0,0,XNA,0.822037,0.737448,0.488455,0.0948,0.0445,0.9846,0.7892,0.0290,0.08,0.0345,0.5417,0.5833,0.1152,0.0765,0.0847,0.0039,0.0247,0.0966,0.0462,0.9846,0.7975,0.0293,0.0806,0.0345,0.5417,0.5833,0.1178,0.0836,0.0882,0.0039,0.0262,0.0958,0.0445,0.9846,0.7920,0.0292,0.08,0.0345,0.5417,0.5833,0.1172,0.0778,0.0862,0.0039,0.0253,reg oper account,block of flats,0.0720,Block,No,1.0,0.0,1.0,0.0,-532.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
220727,355702,0,Cash loans,F,N,N,0,81000.0,191880.0,17883.0,180000.0,Unaccompanied,Pensioner,Secondary / secondary special,Separated,House / apartment,0.018634,-20811,365243,-4629.0,-4252,NaN,1,0,0,1,0,1,NaN,1.0,2,2,WEDNESDAY,12,0,0,0,0,0,0,XNA,NaN,0.623622,0.713631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1840.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
118984,237969,0,Cash loans,M,Y,Y,0,225000.0,1024740.0,55719.0,900000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.003813,-9199,-1398,-710.0,-1622,7.0,1,1,0,1,0,0,Laborers,2.0,2,2,MONDAY,8,0,0,0,0,1,1,Business Entity Type 2,NaN,0.629338,0.661024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.0,8.0,0.0,-541.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
99909,215991,0,Cash loans,F,N,N,0,90000.0,327024.0,15241.5,270000.0,Unaccompanied,Commercial associate,Higher education,Single / not married,Rented apartment,0.010500,-11871,-128,-4549.0,-4548,NaN,1,1,0,1,0,0,Core staff,1.0,3,3,MONDAY,19,0,0,0,1,1,0,Business Entity Type 2,0.159918,0.559240,0.436506,0.0825,0.0735,0.9851,0.7960,0.0359,0.00,0.2069,0.1667,0.0417,0.1288,0.0672,0.0804,0.0000,0.0000,0.0840,0.0762,0.9851,0.8040,0.0362,0.0000,0.2069,0.1667,0.0417,0.1317,0.0735,0.0837,0.0000,0.0000,0.0833,0.0735,0.9851,0.7987,0.0361,0.00,0.2069,0.1667,0.0417,0.1310,0.0684,0.0818,0.0000,0.0000,reg oper account,block of flats,0.0923,"Stone, brick",No,0.0,0.0,0.0,0.0,-599.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
108270,225596,0,Cash loans,M,Y,Y,2,288000.0,1187370.0,115803.0,1125000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.018850,-17352,-3625,-1558.0,-903,3.0,1,1,0,1,0,0,Managers,4.0,2,2,TUESDAY,9,0,0,0,0,0,0,Self-employed,0.425319,0.684615,0.751724,0.1093,0.0512,0.9975,NaN,NaN,0.12,0.1034,0.3333,NaN,0.0211,NaN,0.1371,NaN,0.0632,0.1113,0.0531,0.9975,NaN,NaN,0.1208,0.1034,0.3333,NaN,0.0216,NaN,0.1428,NaN,0.0669,0.1103,0.0512,0.9975,NaN,NaN,0.12,0.1034,0.3333,NaN,0.0215,NaN,0.1396,NaN,0.0645,NaN,block of flats,0.1385,"Stone, brick",No,0.0,0.0,0.0,0.0,-2287.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
65901,176414,0,Cash loans,F,N,N,0,90000.0,467257.5,21910.5,328500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,With parents,0.003122,-10302,-2010,-593.0,-2159,NaN,1,1,0,1,0,0,Sales staff,2.0,3,3,MONDAY,14,0,0,0,0,0,0,Self-employed,NaN,0.220263,0.569149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1153.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
223010,358310,0,Cash loans,F,N,Y,1,135000.0,450000.0,16294.5,450000.0,Unaccompanied,State servant,Secondary / secondary special,Married,House / apartment,0.022800,-16215,-4717,-61.0,-1561,NaN,1,1,0,1,0,0,NaN,3.0,2,2,WEDNESDAY,9,0,0,0,0,0,0,Security Ministries,NaN,0.712204,0.812823,0.0928,0.0844,0.9846,NaN,NaN,0.00,0.2069,0.1667,NaN,0.0729,NaN,0.0768,NaN,0.0000,0.0945,0.0875,0.9846,NaN,NaN,0.0000,0.2069,0.1667,NaN,0.0745,NaN,0.0800,NaN,0.0000,0.0937,0.0844,0.9846,NaN,NaN,0.00,0.2069,0.1667,NaN,0.0742,NaN,0.0782,NaN,0.0000,NaN,block of flats,0.0670,"Stone, brick",No,0.0,0.0,0.0,0.0,-1384.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
133464,254791,0,Cash loans,F,N,Y,0,42367.5,808650.0,23773.5,675000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.002134,-18395,365243,-3580.0,-1866,NaN,1,0,0,1,0,0,NaN,2.0,3,3,TUESDAY,11,0,0,0,0,0,0,XNA,NaN,0.657409,NaN,0.0577,NaN,0.9816,NaN,NaN,0.00,0.1379,0.1667,NaN,NaN,NaN,0.0664,NaN,0.0156,0.0588,NaN,0.9816,NaN,NaN,0.0000,0.1379,0.1667,NaN,NaN,NaN,0.0692,NaN,0.0165,0.0583,NaN,0.9816,NaN,NaN,0.00,0.1379,0.1667,NaN,NaN,NaN,0.0676,NaN,0.0159,NaN,block of flats,0.0555,"Stone, brick",No,0.0,0.0,0.0,0.0,-963.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
19497,122737,0,Cash loans,M,Y,Y,0,270000.0,484861.5,35410.5,396000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.002134,-10597,-1188,-812.0,-3144,14.0,1,1,0,1,0,0,NaN,2.0,3,3,FRIDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.177553,0.514928,0.574447,0.1237,0.1418,0.9980,0.9728,0.2894,0.00,0.2414,0.1667,0.0417,0.0319,0.1009,0.1904,0.0000,0.0388,0.1261,0.1471,0.9980,0.9739,0.2920,0.0000,0.2414,0.1667,0.0417,0.0326,0.1102,0.1984,0.0000,0.0411,0.1249,0.1418,0.9980,0.9732,0.2912,0.00,0.2414,0.1667,0.0417,0.0324,0.1026,0.1938,0.0000,0.0396,reg oper account,block of flats,0.1582,"Stone, brick",No,2.0,1.0,2.0,1.0,-827.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,2.0,0.0
135910,257642,0,Cash loans,F,N,N,0,112500.0,900000.0,46084.5,900000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.028663,-12587,-4995,-3583.0,-4283,NaN,1,1,0,1,0,0,High skill tech staff,2.0,2,2,SUNDAY,12,0,0,0,0,1,1,Medicine,NaN,0.186833,0.461482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0.0,5.0,0.0,-909.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
260919,401956,0,Cash loans,M,Y,N,0,225000.0,225000.0,15219.0,225000.0,Unaccompanied,Working,Incomplete higher,Single / not married,House / apartment,0.024610,-9171,-1310,-3919.0,-1836,4.0,1,1,1,1,1,0,Laborers,1.0,2,2,WEDNESDAY,15,0,0,0,0,0,0,Business Entity Type 3,0.243624,0.615313,0.288130,0.1196,NaN,0.9866,NaN,0.0185,NaN,NaN,NaN,NaN,0.0262,0.0958,0.0734,0.0077,0.0532,0.1218,NaN,0.9866,NaN,0.0187,NaN,NaN,NaN,NaN,0.0268,0.1047,0.0765,0.0078,0.0563,0.1207,NaN,0.9866,NaN,0.0187,NaN,NaN,NaN,NaN,0.0266,0.0975,0.0747,0.0078,0.0543,NaN,NaN,0.0794,NaN,No,0.0,0.0,0.0,0.0,-1092.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
245313,383907,0,Cash loans,M,N,N,0,171000.0,728460.0,40675.5,675000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Single / not married,With parents,0.046220,-14128,-1288,-8042.0,-2187,NaN,1,1,0,1,1,1,NaN,1.0,1,1,THURSDAY,13,0,0,0,0,1,1,Business Entity Type 3,NaN,0.376884,0.372334,0.0186,0.0556,0.9811,0.7416,0.0393,0.00,0.1034,0.0417,0.0833,0.0727,0.0151,0.0102,0.0000,0.0000,0.0189,0.0577,0.9811,0.7517,0.0397,0.0000,0.1034,0.0417,0.0833,0.0743,0.0165,0.0106,0.0000,0.0000,0.0187,0.0556,0.9811,0.7451,0.0396,0.00,0.1034,0.0417,0.0833,0.0739,0.0154,0.0104,0.0000,0.0000,reg oper account,block of flats,0.0139,"Stone, brick",No,0.0,0.0,0.0,0.0,-1415.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0
87795,201914,0,Cash loans,M,N,Y,0,112500.0,1042560.0,34587.0,900000.0,Unaccompanied,Working,Secondary / secondary special,Widow,House / apartment,0.024610,-20180,-319,-9518.0,-3645,NaN,1,1,1,1,0,0,Laborers,1.0,2,2,WEDNESDAY,11,0,0,0,0,0,0,Business Entity Type 3,NaN,0.611096,0.321735,0.0278,0.0655,0.9871,NaN,NaN,0.00,0.1034,0.0833,NaN,0.0101,NaN,0.0310,NaN,0.0000,0.0284,0.0679,0.9871,NaN,NaN,0.0000,0.1034,0.0833,NaN,0.0103,NaN,0.0323,NaN,0.0000,0.0281,0.0655,0.9871,NaN,NaN,0.00,0.1034,0.0833,NaN,0.0102,NaN,0.0315,NaN,0.0000,NaN,block of flats,0.0244,"Stone, brick",No,0.0,0.0,0.0,0.0,-1531.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,3.0,2.0
266472,408713,0,Cash loans,F,N,N,0,405000.0,679500.0,66195.0,679500.0,Unaccompanied,Commercial associate,Higher education,Widow,House / apartment,0.032561,-23097,-1829,-1824.0,-3967,NaN,1,1,1,1,0,0,Accountants,1.0,1,1,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,0.916679,0.702243,0.472253,0.1546,0.0923,0.9960,NaN,NaN,0.16,0.0690,0.6250,NaN,NaN,NaN,0.1962,NaN,0.0629,0.1576,0.0958,0.9960,NaN,NaN,0.1611,0.0690,0.6250,NaN,NaN,NaN,0.2045,NaN,0.0666,0.1561,0.0923,0.9960,NaN,NaN,0.16,0.0690,0.6250,NaN,NaN,NaN,0.1998,NaN,0.0642,NaN,block of flats,0.1695,Panel,No,1.0,0.0,1.0,0.0,-367.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
224329,359830,0,Cash loans,F,N,N,2,202500.0,667422.0,46449.0,630000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.031329,-13712,-1888,-638.0,-2500,NaN,1,1,1,1,0,0,Managers,4.0,2,2,FRIDAY,12,0,0,0,0,1,1,Trade: type 7,NaN,0.691476,0.629674,0.0278,0.0468,0.9727,0.6260,0.0392,0.00,0.1034,0.0833,0.1250,0.0243,0.0227,0.0308,0.0000,0.0000,0.0284,0.0486,0.9727,0.6406,0.0396,0.0000,0.1034,0.0833,0.1250,0.0248,0.0248,0.0321,0.0000,0.0000,0.0281,0.0468,0.9727,0.6310,0.0395,0.00,0.1034,0.0833,0.1250,0.0247,0.0231,0.0314,0.0000,0.0000,reg oper account,block of flats,0.0457,Panel,No,0.0,0.0,0.0,0.0,-203.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0

# Bureau

In [ ]:
bureau.sample(20)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
1665395,188518,6651634,Active,currency 1,-666,0,1161.0,NaN,NaN,0,1058823.00,698989.50,0.0,0.0,Consumer credit,-61,0.00
837397,105771,6640560,Closed,currency 1,-250,0,116.0,-38.0,0.0,0,192595.50,0.00,0.0,0.0,Consumer credit,-38,NaN
889079,203128,5817303,Active,currency 1,-233,0,1228.0,NaN,NaN,0,1184211.00,NaN,NaN,0.0,Consumer credit,-21,41953.50
1184665,260194,5526864,Active,currency 1,-141,0,27472.0,NaN,NaN,0,22500.00,23220.00,0.0,0.0,Credit card,-11,NaN
254120,186984,5839288,Active,currency 1,-32,0,151.0,NaN,0.0,0,58379.31,58379.31,0.0,0.0,Consumer credit,-31,7274.25
880001,151822,6286584,Closed,currency 1,-890,0,-708.0,-707.0,0.0,0,90810.00,0.00,0.0,0.0,Consumer credit,-702,NaN
255042,346337,5840418,Active,currency 1,-28,0,NaN,NaN,NaN,0,360000.00,361417.50,NaN,0.0,Consumer credit,-20,NaN
495708,188043,6441332,Active,currency 1,-1660,0,-582.0,NaN,0.0,0,0.00,0.00,0.0,0.0,Credit card,-34,NaN
845259,250349,6275374,Closed,currency 1,-1603,0,-1392.0,-983.0,NaN,0,29875.50,NaN,NaN,0.0,Consumer credit,-980,NaN
1669998,144603,5602823,Closed,currency 1,-346,0,-72.0,-72.0,0.0,0,163791.00,0.00,0.0,0.0,Consumer credit,-67,27927.00
789151,309438,6500008,Active,currency 1,-1177,0,NaN,NaN,0.0,0,0.00,0.00,0.0,0.0,Credit card,-20,NaN
499316,337490,6413350,Active,currency 1,-1314,0,NaN,NaN,NaN,0,22500.00,0.00,0.0,0.0,Credit card,-1310,NaN
1073736,254887,5927348,Closed,currency 1,-2727,0,-2397.0,-2397.0,NaN,0,44955.00,0.00,0.0,0.0,Consumer credit,-2382,NaN
964747,222355,6760788,Closed,currency 1,-345,0,11.0,-20.0,NaN,0,98577.00,0.00,0.0,0.0,Consumer credit,-18,NaN
257138,285681,5842955,Closed,currency 1,-216,0,-200.0,-206.0,NaN,0,4500.00,0.00,0.0,0.0,Consumer credit,-201,0.00
204552,373520,5835747,Active,currency 1,-734,0,4804.0,NaN,NaN,0,0.00,49567.50,NaN,0.0,Credit card,-21,NaN
1507819,433277,5996200,Closed,currency 1,-1734,0,-1369.0,-1368.0,NaN,0,118822.50,0.00,NaN,0.0,Consumer credit,-1366,0.00
232226,320586,5847402,Closed,currency 1,-971,0,-788.0,-771.0,NaN,0,231858.00,NaN,NaN,0.0,Consumer credit,-768,NaN
57488,450215,5235531,Active,currency 1,-2878,0,-1773.0,NaN,0.0,0,135000.00,0.00,0.0,0.0,Credit card,-596,NaN
1397035,292888,5284150,Closed,currency 1,-2044,0,-1782.0,-1105.0,NaN,0,66150.00,0.00,NaN,0.0,Consumer credit,-1105,NaN

# Bureau Balance

In [ ]:
bureau_balance.sample(20)

          SK_ID_BUREAU  MONTHS_BALANCE STATUS
2081812        5061426             -51      X
12523829       5879098             -12      C
7134039        5731751             -32      C
22251432       6326836             -68      C
2611879        5833532              -6      C
6389703        6025026              -6      C
2389079        6566251             -20      X
10531          5720142             -34      X
22007765       6206881             -20      0
10500452       6308650             -30      C
23817108       6737828             -28      C
2105489        6011152             -46      0
20193576       6820824             -96      C
14009847       6466779             -56      C
4662708        6801252             -92      C
27153177       6646608             -12      X
8987082        6093407             -25      X
14229382       6272595             -49      X
5625391        6037323             -54      0
24509815       6659098              -4      X

# POS CASH Balance

In [ ]:
POS_CASH_balance.sample(20)

         SK_ID_PREV  SK_ID_CURR  ...  SK_DPD  SK_DPD_DEF
2268647     1316555      449796  ...       0           0
3511415     2673146      237224  ...       0           0
8159894     2119673      197941  ...       0           0
2403578     2121060      292156  ...       0           0
564102      1460593      310029  ...       0           0
4862737     1589055      432192  ...       0           0
8851554     1441865      206328  ...       0           0
7658267     2271124      238364  ...       0           0
7359607     1938282      286577  ...       0           0
2081354     2391226      157288  ...       0           0
1993132     2795987      109010  ...       0           0
6123150     1656179      358322  ...       0           0
8122981     2295432      369845  ...       0           0
8953787     2644480      155215  ...       0           0
7507235     2127883      438697  ...       0           0
6766579     2552449      275287  ...       0           0
9103017     1464419      146883  ...       0           0
135279      1239593      258320  ...       0           0
3811394     2137244      147744  ...       0           0
188495      2327732      440929  ...       0           0

[20 rows x 8 columns]

# Credit Card Balance

In [ ]:
credit_card_balance.sample(20)

         SK_ID_PREV  SK_ID_CURR  ...  SK_DPD  SK_DPD_DEF
2816233     2403074      136963  ...       0           0
1406779     1499273      236077  ...       0           0
2957617     2366477      371309  ...       0           0
798152      2709164      263929  ...       0           0
290862      1311115      453888  ...       0           0
3074131     2664922      202739  ...       0           0
2673216     1951713      435371  ...       0           0
2881515     1969006      137137  ...       0           0
3300554     2592886      209784  ...       0           0
1250380     1386385      288261  ...       0           0
1756546     2110824      129974  ...       0           0
3105832     1488143      346810  ...       0           0
2550964     1317160      111178  ...       0           0
899707      2313973      371966  ...       0           0
864455      2623501      341795  ...       0           0
3235964     2628692      277508  ...       0           0
865351      2208293      384091  ...       0           0
202076      1850264      320803  ...       0           0
2294331     1976633      238542  ...       0           0
1056220     2705437      200751  ...       0           0

[20 rows x 23 columns]

# Previous Application

In [ ]:
previous_application.sample(20)

         SK_ID_PREV  SK_ID_CURR  ... DAYS_TERMINATION  NFLAG_INSURED_ON_APPROVAL
208810      2358568      147615  ...              NaN                        NaN
1525529     2008024      174634  ...           -778.0                        0.0
1057244     1315009      420610  ...         365243.0                        0.0
81017       1405460      402188  ...         365243.0                        0.0
775936      1368955      239179  ...           -935.0                        0.0
1463307     2276349      173139  ...              NaN                        NaN
251127      1111583      268801  ...           -457.0                        0.0
1585409     2187049      394748  ...              NaN                        NaN
54356       1288498      415449  ...         365243.0                        0.0
1498563     2817196      212606  ...          -1101.0                        0.0
1480799     2295373      168878  ...              NaN                        NaN
437974      1796977      133720  ...         365243.0                        0.0
710885      2471608      122473  ...           -214.0                        0.0
318853      1336023      257448  ...         365243.0                        1.0
17320       2599521      441983  ...              NaN                        NaN
1055624     1737220      371432  ...              NaN                        NaN
191098      2113134      161368  ...              NaN                        NaN
99217       2036824      415206  ...              NaN                        NaN
1289265     2263237      354752  ...          -1568.0                        0.0
349820      1789054      104999  ...          -1101.0                        0.0

[20 rows x 37 columns]

# Installments Payments

In [ ]:
installments_payments.sample(20)

          SK_ID_PREV  SK_ID_CURR  ...  AMT_INSTALMENT  AMT_PAYMENT
2435707      1975291      130967  ...        1776.105     1776.105
6023733      2500248      290882  ...       14060.250    14060.250
6716855      2323138      208375  ...       20838.600    20838.600
4907131      1855480      276102  ...       18202.185    18202.185
179946       1231605      166211  ...       11048.535    11048.535
5077728      1155157      284871  ...       25481.745    25481.745
5354257      1052998      270375  ...      251872.290   251872.290
6852129      1830252      208115  ...       15998.940    15998.940
10090969     1596012      355948  ...        6750.000     6750.000
612640       1959374      156402  ...        3375.000     3375.000
5392135      1793041      261945  ...        2250.000     2250.000
7460537      1748696      213950  ...       18486.270    18486.270
13471745     2286212      445854  ...      560634.750   560634.750
2931521      2572256      171757  ...       16655.355    16655.355
3000192      1596013      197620  ...         224.865      224.865
1946654      2560396      194632  ...       15488.325    14055.210
2691353      2100938      109075  ...      978969.960   978969.960
12121207     1209869      435702  ...          97.785       97.785
5302310      2820740      202726  ...        1003.455     1003.455
1584288      2274233      121276  ...        6127.560     6127.560

[20 rows x 8 columns]